//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralSentRequest
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public string MaterialSubCategory { get; set; }
        public int VendorID { get; set; }
        public int AccountantID { get; set; }
        public decimal PricePerQuantity { get; set; }
        public int OrderedQuantity { get; set; }
        public string Address { get; set; }
        public System.DateTime OrderedDate { get; set; }
        public Nullable<int> CentralPurchaseDepartmentID { get; set; }
        public string Status { get; set; }
        public Nullable<int> IssuingQuantity { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string Remarks { get; set; }
    }
}
