//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralPurchaseOrderItem
    {
        public int POItemID { get; set; }
        public Nullable<int> PONumber { get; set; }
        public Nullable<int> QtyOrdered { get; set; }
        public Nullable<int> QtyReceived { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string VendorEmail { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AcceptedQty { get; set; }
        public Nullable<int> RejectedQty { get; set; }
        public string Unit { get; set; }
        public string Make { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string SummarizerID { get; set; }
        public string Statement { get; set; }
        public string CentralAccountantID { get; set; }
        public string Status { get; set; }
    
        public virtual CentralPurchaseOrder CentralPurchaseOrder { get; set; }
    }
}
