//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralPurchaseDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentralPurchaseDepartment()
        {
            this.StoreRequestingMaterials = new HashSet<StoreRequestingMaterial>();
        }
    
        public int CID { get; set; }
        public Nullable<int> CentralAccountantID { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> CITID { get; set; }
        public string CentralDepartmentName { get; set; }
        public string CentralDepartmentPhone { get; set; }
        public string CentralDepartmentEmail { get; set; }
        public string CentralDepartmentAddress { get; set; }
        public string CentralID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreRequestingMaterial> StoreRequestingMaterials { get; set; }
    }
}
