//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralAccountantReport
    {
        public int ReportID { get; set; }
        public int RequestID { get; set; }
        public int VendorID { get; set; }
        public decimal RequestingAmount { get; set; }
        public decimal SettledAmount { get; set; }
        public System.DateTime SettledDate { get; set; }
    }
}
