//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeIssueMaterial
    {
        public int IssueID { get; set; }
        public int RequestID { get; set; }
        public string EmpID { get; set; }
        public string HODID { get; set; }
        public string AssetType { get; set; }
        public string MaterialCategory { get; set; }
        public string MaterialSubCategory { get; set; }
        public int RequestingQuantity { get; set; }
        public int ApprovedQuantity { get; set; }
        public int AvailableQuantity { get; set; }
        public int IssuingQuantity { get; set; }
        public int ClosingQuantity { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public string IssuedBy { get; set; }
        public string Status { get; set; }
        public Nullable<int> PreviousIssuingQuantity { get; set; }
        public Nullable<int> Issue { get; set; }
    }
}
