//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HODRequest
    {
        public int SNO { get; set; }
        public string HODID { get; set; }
        public string AssetType { get; set; }
        public string MaterialCategory { get; set; }
        public string MSubCategory { get; set; }
        public int RequestingQuantity { get; set; }
        public Nullable<int> IssuingQuantity { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string StoreAdminID { get; set; }
        public string PendingQuantity { get; set; }
        public string Status { get; set; }
        public Nullable<int> HODRequestID { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
    }
}
