//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsertCentralPurchaseDepartment
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public string MaterialSubCategory { get; set; }
        public int RequestingQuantity { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<int> CPDID { get; set; }
        public string Address { get; set; }
    
        public virtual RequestingMaterial RequestingMaterial { get; set; }
    }
}
