//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalPurchased
    {
        public int ID { get; set; }
        public int LocalID { get; set; }
        public int VendorID { get; set; }
        public int UniversityID { get; set; }
        public string Material { get; set; }
        public int Order_Quantity { get; set; }
        public string Vendor_EmailID { get; set; }
        public decimal PricePerQuantity { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime Ordered_Date { get; set; }
    }
}
