//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalPurchaseDepartment
    {
        public int LID { get; set; }
        public int UniversityID { get; set; }
        public Nullable<int> LocalAccountantID { get; set; }
        public string EmailID { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string LocalID { get; set; }
    
        public virtual University University { get; set; }
    }
}
