//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalAccountantReport
    {
        public int ReportID { get; set; }
        public int RequestID { get; set; }
        public int UniversityID { get; set; }
        public string UniversityName { get; set; }
        public decimal RequestingAmount { get; set; }
        public decimal SettledAmount { get; set; }
        public System.DateTime SettledDate { get; set; }
        public Nullable<int> VendorID { get; set; }
    
        public virtual RequestingMaterial RequestingMaterial { get; set; }
        public virtual University University { get; set; }
    }
}
