//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialSubCategory
    {
        public int MSubCategoryID { get; set; }
        public string MaterialSubCategory1 { get; set; }
        public int MID { get; set; }
    
        public virtual MaterialCategory MaterialCategory { get; set; }
    }
}
