//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int SNO { get; set; }
        public string EmpID { get; set; }
        public string AssetType { get; set; }
        public string MaterialCategory { get; set; }
        public string MSubCategory { get; set; }
        public int RequestingQuantity { get; set; }
        public Nullable<int> ApprovedQuantity { get; set; }
        public Nullable<int> IssuingQuantity { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string HODID { get; set; }
        public string Status { get; set; }
        public string StoreAdminID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public Nullable<int> PendingQuantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ClosingQuantity { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<int> Issue { get; set; }
    }
}
