//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestingMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestingMaterial()
        {
            this.CentralAccountantReports = new HashSet<CentralAccountantReport>();
            this.InsertCentralPurchaseDepartments = new HashSet<InsertCentralPurchaseDepartment>();
            this.InsertLocalPurchaseDepartments = new HashSet<InsertLocalPurchaseDepartment>();
            this.LocalAccountantReports = new HashSet<LocalAccountantReport>();
        }
    
        public int RequestID { get; set; }
        public string AssetType { get; set; }
        public string MaterialCategory { get; set; }
        public string MaterialSubCategory { get; set; }
        public int RequestingQuantity { get; set; }
        public string Status { get; set; }
        public int StoreAdminID { get; set; }
        public int UniversityID { get; set; }
        public int PurchaseDepartmentID { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentralAccountantReport> CentralAccountantReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsertCentralPurchaseDepartment> InsertCentralPurchaseDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsertLocalPurchaseDepartment> InsertLocalPurchaseDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalAccountantReport> LocalAccountantReports { get; set; }
    }
}
