//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiredMaterial
    {
        public int RequiredMaterialID { get; set; }
        public string AssetType { get; set; }
        public string MaterialCategory { get; set; }
        public string MaterialSubCategory { get; set; }
        public int UserID { get; set; }
        public int StoreAdminID { get; set; }
        public string Role { get; set; }
        public Nullable<int> RequiredQuantity { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string Status { get; set; }
    }
}
