//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavetoCentral
    {
        public int ID { get; set; }
        public string LocalID { get; set; }
        public int UniversityID { get; set; }
        public string CentralID { get; set; }
        public string Material { get; set; }
        public int Order_Quantity { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string Status { get; set; }
        public string PurchaseDepartmentUploads { get; set; }
    }
}
