//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreAdmin
    {
        public int SAID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string PhoneNumber { get; set; }
        public int UniversityID { get; set; }
        public string DepName { get; set; }
        public Nullable<int> DepID { get; set; }
        public string StoreAdminID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual University University { get; set; }
    }
}
