//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreRequestingMaterial
    {
        public int ID { get; set; }
        public string AssetType { get; set; }
        public string MaterialCategory { get; set; }
        public string MaterialSubCategory { get; set; }
        public int RequestingQuantity { get; set; }
        public int UniversityID { get; set; }
        public int LocalID { get; set; }
        public decimal QuotationAmount { get; set; }
        public int CentralID { get; set; }
        public int LocalAccountantID { get; set; }
        public int CentralAccountantID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    
        public virtual CentralAccountant CentralAccountant { get; set; }
        public virtual CentralPurchaseDepartment CentralPurchaseDepartment { get; set; }
        public virtual LocalAccountant LocalAccountant { get; set; }
        public virtual LocalPurchaseDepartment LocalPurchaseDepartment { get; set; }
        public virtual University University { get; set; }
    }
}
