//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempSelectedMaterial
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string MaterialSubCategory { get; set; }
        public string Status { get; set; }
        public string UniversityID { get; set; }
    }
}
